"""Updates db with initial fields required for MVP

Revision ID: c990ad709068
Revises: f4389a0b7352
Create Date: 2018-02-02 07:25:28.714132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c990ad709068'
down_revision = 'f4389a0b7352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('last_call', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=128), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_call')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
